### ISSUE TITLE
Update README with description and documentation on how to use

### ISSUE THREAD

**Issue by GroovinChip** [emostar/flutter-libphonenumber#1]
If I understand the purpose of this package correctly, this is exactly what I've been needing - a way to auto format phone numbers based on locale. However, the readme contains almost no information.

**Comment by CoreyCole** [comment]
The underlying google library that this plugin depends on is google's libphonenumber. In the FAQ on that main repo, it looks like they advise against auto formatting numbers based on locale? https://github.com/google/libphonenumber/blob/master/FAQ.md#formatting

So it probably cannot do what you need it to do? Not sure

**Comment by aytunch** [comment]
@CoreyCole what about the iOS native implementation? Which library or kit is being used? Some info would have been very good.

**Comment by CoreyCole** [comment]
@aytunch it is also lib phone number on iOS as you can see here:
https://github.com/emostar/flutter-libphonenumber/blob/master/ios/libphonenumber.podspec#L18

Here is the pods page:
https://cocoapods.org/pods/libPhoneNumber-ios
