### ISSUE TITLE
Publish the latest PR

### ISSUE THREAD

**Issue by natintosh** [emostar/flutter-libphonenumber#11]
Hello @emostar 👋  could you please publish the latest PR as I have a package that's dependent on it and pub publish wouldn't lemme publish a package dependent on a git repo. Thanks

**Comment by emostar** [comment]
Hi @natintosh. Are you talking about #4? It looks like there is a conflict, but I'll take a look at it.

**Comment by natintosh** [comment]
Thanks for the response @emostar but I'm taking about #3

**Comment by emostar** [comment]
Ahh ok. I just merged #4 in and will prepare a release that has everything.

**Comment by natintosh** [comment]
Thanks

**Comment by emostar** [comment]
1.0.1 is up at https://pub.dev/packages/libphonenumber and includes #3 and #4.
