### ISSUE TITLE
Unrecognized mobile code (788) for Zimbabwe

### ISSUE THREAD

**Issue by SandeMK** [emostar/flutter-libphonenumber#21]
+263 as the country code, this mobile number 788930137 is not recognized, and the is_not_valid error is thrown for a valid combination.

**Comment by aloism** [comment]
exactly what i am facing too, its happening on the latest issued mobile phone numbers by service providers.

**Comment by emostar** [comment]
The backend library with the number updates for the world has been updated. This should be working in v1.0.2. Please reopen if it is not.

**Comment by emostar** [comment]
FWIW, I confirmed it is working with the example app included in 1.0.2. It says the carrier is Econet in ZW.
