### ISSUE TITLE
Latest Country phone numbers are not validating

### ISSUE THREAD

**Issue by aloism** [emostar/flutter-libphonenumber#23]
Each country has service provider for mobile phone numbers, so the latest phone number formats are no longer being validated with this library, i suppose its now using an old version of libphonenumber.

It returns false but the number will be correct and using a correct country code.

**Comment by emostar** [comment]
I just updated the core library that has the latest area codes. Can you try with v1.0.2 and verify it works?

**Comment by emostar** [comment]
Should be resolved with latest libphonenumber dependency. If it still does not work, please open a new issue.
