### ISSUE TITLE
Unhandled Exception: type 'Future<dynamic>' is not a subtype of type 'FutureOr<Map<dynamic, dynamic>>' in type cast

### ISSUE THREAD

**Issue by natintosh** [emostar/flutter-libphonenumber#29]
Hi @emostar, 

It seems like the cast you did here is no longer valid 

`PhoneNumberUtil.getRegionInfo (package:libphonenumber/libphonenumber.dart:78:8)`

**Comment by natintosh** [comment]
Hi, @emostar any update for this PR.

**Comment by krunaldoshi2019** [comment]
hi @emostar any update for this PR?

**Comment by ahmedfef** [comment]
This is still not fixed!
You should fix the casting type.

For now, I changed the package files to make it work till they release a proper update for it.
Inside: **\libphonenumber-2.0.0\lib\libphonenumber.dart**

Change the following:
`    Map<dynamic, dynamic> result = await (_channel.invokeMethod('getRegionInfo', {
      'phone_number': phoneNumber,
      'iso_code': isoCode,
    }) as FutureOr<Map<dynamic, dynamic>>);`

To

`    Map<dynamic, dynamic> result = await (_channel.invokeMethod('getRegionInfo', {
      'phone_number': phoneNumber,
      'iso_code': isoCode,
    }) as Future<dynamic>);`
