### ISSUE TITLE
LibphonenumberPlugin.java uses or overrides a deprecated API

### ISSUE THREAD

**Issue by toklive** [emostar/flutter-libphonenumber#32]
Getting the below error while trying to run the app i Android emulator (SDK 28), gradle level minSDK set to 23. Any idea how to fix ?

Launching lib/main.dart on Android SDK built for x86 in debug mode...
lib/main.dart:1
Note: /usr/local/Caskroom/flutter/2.0.3/flutter/.pub-cache/hosted/pub.dartlang.org/libphonenumber-2.0.0/android/src/main/java/com/codeheadlabs/libphonenumber/LibphonenumberPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by toklive** [comment]
Any comments? Thanks

**Comment by emostar** [comment]
This should be related to v1 Android embedding. I am not removing it, just to keep backwards compatibility. v2 is supported as well.
