### ISSUE TITLE
libphonenumber: ^2.0.0 - PhoneNumberUtil.getRegionInfo type 'Future<dynamic>' is not a subtype of type 'FutureOr<Map<dynamic, dynamic>>

### ISSUE THREAD

**Issue by ccamba** [emostar/flutter-libphonenumber#33]
Unhandled Exception: type 'Future<dynamic>' is not a subtype of type 'FutureOr<Map<dynamic, dynamic>>' in type cast
E/flutter (23782): #0      PhoneNumberUtil.getRegionInfo package:libphonenumber/libphonenumber.dart:78

**Comment by bscottsmith** [comment]
After upgrading from 1.0.2 to 2.0.0 this is happening to me, too. Please fix!

**Comment by emostar** [comment]
2.0.1 is live now with this fix.
