### ISSUE TITLE
Mobile number in CIV got changed from 8 to 10 digits

### ISSUE THREAD

**Issue by AhmadKsb** [emostar/flutter-libphonenumber#36]
All ORANGE cell phone numbers after the country code (+225) now start with 07
All MTN cell phone numbers after the country code (+225) now start with 05
All MOOV cell phone numbers after the country code (+225) now start with 01

Can we have this fixed please?

we still haven't upgraded our project to flutter 2.0, can you please verify if this issue is resolved in the newer versions?

**Comment by rehamalraee** [comment]
Hi, is it solved?

**Comment by emostar** [comment]
I just updated to the latest libphonenumber versions, v2.0.2 has been published, so it should be resolved.
