### ISSUE TITLE
uses a deprecated version of the Android embedding

### ISSUE THREAD

**Issue by BrianTum** [emostar/flutter-libphonenumber#38]
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future  
release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by Smithtekk** [comment]
Is there an update to this? @emostar

**Comment by TheHypnoo** [comment]
Flutter 2.5 has been released and when starting it shows the error, do you know anything if it will be solved?

**Comment by HeshamErfanMDLabs** [comment]
The same issue here. It's related to updating to flutter 2.5

**Comment by ngtamphuong** [comment]
I'm facing the same issue. Any update on this?

**Comment by SakhileMamba** [comment]
I'm facing the same issue with flutter 2.5

**Comment by aytunch** [comment]
Is there a fix planned for this?
Flutter 2.5 upgrade caused the error. I guess everyone will see the message soon enough.

**Comment by emostar** [comment]
Fixed in commit 3a9a4ee and v2.0.2 has been published.
