### ISSUE TITLE
Repository still maintained?

### ISSUE THREAD

**Issue by vkammerer** [emostar/flutter-libphonenumber#8]
Hello @emostar ,

Thank you for the plugin, it's the good base I was looking for with my project.

I will need to implement new functionalities so I was thinking about opening new Pull Requests in your repo, but I can see that you haven't replied in months to the ones that have already been opened.

Are you not interested anymore in maintaining this repo? If you are then I will open PRs.

Thank you

**Comment by emostar** [comment]
Hi,

I guess I must have missed the notifications for the issues and PRs, as this is the first time I am seeing anything in this repo.

Yes, please submit a PR for any new functionalities and I'll give feedback and/or merge them in.

**Comment by vkammerer** [comment]
Ok thank you for the quick reply.
I will open in the next week a PR with support for formatting number in batch.
