### ISSUE TITLE
Could you add format number option

### ISSUE THREAD

**Issue by natintosh** [emostar/flutter-libphonenumber#9]
I will very much like have to have an option that formats phone number, thanks

**Comment by emostar** [comment]
Does `formatAsYouType` implement this well enough for you?

**Comment by natintosh** [comment]
Yeah it works well I'm able to format a phone number to it local format

**Comment by mattdarwin** [comment]
I also need this fix, to parse a number to E164 format.  @edwinnyawoli has opened a [PR](https://github.com/emostar/flutter-libphonenumber/pull/25) which will do this.
